packages:
  - packages/*
  - examples/*
  - website
patchedDependencies:
  eslint: patches/eslint.patch
  json-schema-to-markdown@1.1.1: patches/json-schema-to-markdown@1.1.1.patch
overrides:
  '@graphql-eslint/eslint-plugin': workspace:*
  eslint: 9.22.0
  graphql: 16.10.0
  esbuild: 0.25.0
  '@eslint/plugin-kit': 0.3.4
  cookie: 0.7.0
  glob: 11.1.0
  eslint-plugin-unicorn: 56.0.1
  eslint-plugin-mdx: 3.8.1
strictPeerDependencies: false
shellEmulator: true
enablePrePostScripts: true
allowBuilds:
  esbuild: false
  sharp: false
  workerd: false
